site_name: Litestar Fullstack
site_description: Production-ready fullstack Litestar web application
repo_url: https://github.com/kyle-li-dev/litestar-fullstack
repo_name: kyle-li-dev/litestar-fullstack

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - API: api.md
  - Contributing: contributing.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md
  - License: license.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true